version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.0'
      VENDOR: 'zuk'
      CODENAME: 'z2_plus'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack/
    steps:
      - run:
          name: Create & Run a keep-alive shell
          command: |
            # Basic trick to ping every 6 minutes in the background
            cat \<< EOF > /tmp/act.sh
            #!/bin/bash
            while true; do
              echo -e "\n" && sleep 360
            done
            EOF
            chmod a+x /tmp/act.sh
      - run:
          name: Repo Init and Sync
          command: |
            # Set Git Credential
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            git config --global credential.helper store
            echo -e "\n Initialize repo Command"
            repo init -q -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b ${MANIFEST_BRANCH} --depth 1
            echo -e "\n Removing Unimportant Darwin-specific Files from syncing"
            cd .repo/manifests
            sed -i '/darwin/d' default.xml
            ( find . -type f -name '*.xml' | xargs sed -i '/darwin/d' ) || true
            git commit -a -m "Magic" || true
            cd ../
            sed -i '/darwin/d' manifest.xml
            cd ../
            echo -e "\n Syncing it up! Wait for a few minutes..."
            /tmp/act.sh & repo sync -c -q --force-sync --no-clone-bundle --optimized-fetch --prune --no-tags -j$(nproc --all)
            echo -e "\nGetting the Device Tree on place"
            git clone --quiet --progress https://github.com/PitchBlackRecoveryProject/android_device_zuk_z2_plus-pbrp -b PitchBlack device/${VENDOR}/${CODENAME}
            if [[ -n ${PBRP_BRANCH} ]]; then
              rm -rf bootable/recovery
              git clone --quiet --progress https://github.com/PitchBlackRecoveryProject/android_bootable_recovery -b ${PBRP_BRANCH} --single-branch bootable/recovery
            fi
      - run:
          name: Start build
          command: |
            echo -e "\n Build process starting..."
            export ALLOW_MISSING_DEPENDENCIES=true
            make clean || true
            mkdir -p /tmp/log/
            mkdir releases          
            echo -e "\n Building for ${CODENAME} \n\n" 2>&1 > /tmp/log/${CODENAME}.txt
            source build/envsetup.sh 2>&1 >> /tmp/log/${CODENAME}.txt
            lunch omni_${CODENAME}-eng 2>&1 >> /tmp/log/${CODENAME}.txt
            /tmp/act.sh & make -j$(nproc --all) recoveryimage 2>&1 | sudo tee -api /tmp/log/${CODENAME}.txt
            echo -e "\n Build successful \n\n" 2>&1 >> /tmp/log/${CODENAME}.txt
            mkdir -p releases/${CODENAME} || true
            export BUILDFILE=$(find $(pwd)/out/target/product/${CODENAME}/PitchBlack*.zip 2>/dev/null)
            cp ${BUILDFILE} releases/${CODENAME}/
            ( curl -F "file=@${BUILDFILE}" https://file.io; echo -e "\n" ) || echo -e "\nfile.io upload error for ${CODENAME}\n"
            tar -cJf releases/all_logs.tar.xz /tmp/log/*.txt
            ( curl -F "file=@releases/all_logs.tar.xz" https://file.io; echo -e "\n" ) || echo -e "\nfile.io upload error for logs\n"
            du -sh releases/*

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'tester'
